#Connection To database
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/projet_app?currentSchema=public
    username: postgres
    password: root
    hikari:
      maximumPoolSize: 5
      connectionTimeout: 3000

# The SQL dialect makes Hibernate generate better SQL for the chosen database
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        temp:
          use_jdbc_metadata_defaults: false

# Hibernate ddl auto (create, create-drop, validate, update)
    hibernate:
      ddl-auto: update
      
  jackson:
    serialization:
      fail-on-empty-beans: false

  application:
    name: Project

## Banner config
  banner:
    location: classpath:config/banner/banner-dev.txt
  main:
    log-startup-info: false
  output:
    ansi:
      enabled: always

# Server
server:
  port: 8199
  servlet:
    context-path: /project/api
  ssl:
    enabled: true
    key-store: classpath:config/keystore.p12
    key-store-password: yassine
    keyStoreType: PKCS12
    
# Token
jwt:
  secret: Project@@**2K20
  ms: 86400000
  
#management:
#  endpoints:
#    enabled-by-default: false
#  info:
#    enabled: true
#  metrics:
#    enabled: true

#springdoc:
#  show-actuator: true
#  cache:
#    disabled: true  
#  model-and-view-allowed: true
 